version: '3'
services:
  vault:
    image: vault:1.13.3
    restart: always
    ports:
      - 8200:8200
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_API_ADDR: https://vault.qytopensource.com:8200
      VAULT_LOCAL_CONFIG: '{
        "storage": {"file": {"path": "/vault/file"}},
        "listener": [{"tcp": { "address": "0.0.0.0:8200",
                               "tls_cert_file": "/opt/certs/server.pem",
                               "tls_key_file": "/opt/certs/server-key.pem",
                               "tls_disable": false,
                               "tls_disable_client_certs": true
                               }}],
        "default_lease_ttl": "87600h",
        "max_lease_ttl": "175200h",
        "ui": true
      }'
    command: server
    volumes:
      - vault_logs:/vault/logs
      - vault_file:/vault/file
      - ./server.pem:/opt/certs/server.pem
      - ./server-key.pem:/opt/certs/server-key.pem

volumes:
  vault_logs:
  vault_file:
