- device_ip: 10.1.1.251
  device_type: huawei_vrp
  username: qytang
  password: Huawei@123
  configs:
    - config_direction: ospf
      config_data:
        process_id: 1
        router_id: 3.3.3.3
        area_list:
          - area_id: 0.0.0.0
            area_network_list:
              - network: 10.1.1.0
                wildcard_mask: 0.0.0.255
    - config_direction: users
      config_data:
        users:
          - username: qytang-user1
            password: Huawe@i123
#            priv: 15  # AR支持最多15级
            priv: 3  # CE最多只有3级
            services:
              - telnet
              - ssh
          - username: qytang-user2
            password: Huawei@123
#            priv: 15  # AR支持最多15级
            priv: 3  # CE最多只有3级
            services:
              - telnet
              - ssh

- device_ip: 10.1.1.252
  device_type: huawei_vrp
  username: qytang
  password: Huawei@123
  configs:
    - config_direction: ospf
      config_data:
        process_id: 1
        router_id: 3.3.3.3
        area_list:
          - area_id: 0.0.0.0
            area_network_list:
              - network: 10.1.1.0
                wildcard_mask: 0.0.0.255
              - network: 10.1.2.0
                wildcard_mask: 0.0.0.255
    - config_direction: users
      config_data:
        users:
          - username: qytang-user3
            password: Huawei@123
#            priv: 15  # AR支持最多15级
            priv: 3  # CE最多只有3级
            services:
              - telnet
              - ssh
          - username: qytang-user4
            password: Huawei@123
#            priv: 15  # AR支持最多15级
            priv: 3  # CE最多只有3级
            services:
              - telnet
              - ssh

- device_ip: 10.1.1.254
  device_type: huawei_vrp
  username: qytang
  password: Huawei@123
  configs:
    - config_direction: ospf
      config_data:
        process_id: 1
        router_id: 3.3.3.3
        area_list:
          - area_id: 0.0.0.0
            area_network_list:
              - network: 10.1.1.0
                wildcard_mask: 0.0.0.255
              - network: 10.1.2.0
                wildcard_mask: 0.0.0.255
              - network: 10.1.3.0
                wildcard_mask: 0.0.0.255
    - config_direction: users
      config_data:
        users:
          - username: qytang-user5
            password: Huawei@123
#            priv: 15  # AR支持最多15级
            priv: 3  # CE最多只有3级
            services:
              - telnet
              - ssh
          - username: qytang-user6
            password: Huawei@123
#            priv: 15  # AR支持最多15级
            priv: 3  # CE最多只有3级
            services:
              - telnet
              - ssh